octopusthink/nautilus

docs/form.md, docs/foundation.md, docs/function.md, docs/introduction.md, docs/typographyVariables.md, src/base/spacing.js, src/base/typography/fontSizes.js, src/base/typography/fonts.js, src/base/typography/typography.js, src/base/typography/typographyVariables.js, src/components.js, src/components/typography/Heading/Heading.js, src/components/typography/Heading/Heading.styles.js, src/components/typography/Paragraph/Paragraph.styles.js, src/global.css, styleguide-ui/VariableTable.js, styleguide.config.js
This is going to require a bit more work to get right, since it doesn't feel like it's totally working just yet.
Thinking to have Nautilus provide a "palette" of font variants (weight, size, family, variant, etc) that are then picked-and-chosen by the brand to form a functional/semantic palette, defined by usage.
- Heading (S, M, L) Used for primary headings throughout
- Subheading (M, L) Used for an additional, secondary heading
- Metadata (S, M) Used for small pieces of categorical data (date, tag). Often paired with a heading as an overline style.
- Body (S, M, L) Used for blocks of body text.
- Instruction (M, L) Used to communicate messages or instructions from the system to the user. (Label, Notice)
- Input (M, L) Used when the user inputs messages to the system. (Text field, …
=> Take a first pass at defining typography.

src/components/Button/index.js, src/components/Paragraph/README.md, src/components/Paragraph/index.js, src/themes/mixins.js, src/themes/nautilus/index.js
Closes #19. 
This implements a baseline paragraph component + documentation. 
For future iterations, I'd like to be able to do the following:
- Change the bottom-margin (only)
- Add a drop cap styling (I do love a good drop cap)
- Change the colour (right now, it's just using default browser colour)
I'm wondering if maybe I should address the text colour issue now, rather than later. I'm thinking we should add a theme variable(s) for text colour—probably a few actually. Something like:
- TextColour, TextColourDark, TextColourLight
- TextColourInverse, TextColourInverseDark, TextColourInverseLight (for on dark backgrounds)
That would probably give us enough to play with, and they'd all be various shades of gray from the palette, but you could also pass whatever colour you wanted over.
=> Add a paragraph component

package-lock.json, package.json, src/components/List/Heading.js, src/components/List/Item.js, src/components/List/Paragraph.js, src/components/List/README.md, src/components/List/__snapshots__/index.test.js.snap, src/components/List/index.js, src/components/List/index.test.js, src/components/Paragraph/index.js, src/themes/mixins.js
Closes #50.
Draft of docs here: https://www.notion.so/octopusthink/List-1645bf94c66740ce805382c99be83de4
I've made it so it just borrows a bunch of props from the Paragraph component, since it would make sense to style these similarly. It does mean we're basically repeating a whole bunch of code, so we may end up wanting to have some sort of base Text component for components like these at some point (Quote comes to mind, for instance, although that might use slightly different styling, so maybe not?) but for now some repetition is probably fine. 
Here's what else I think we need here:
I've tagged you in the items I'm not sure how to handle, but I may need help with the other ones too—I'm going to see how far I get now.
For the last item especially, I'm not sure how to do this exactly. 
I …
=> Add List component

src/components/PageTitle/README.md, src/components/PageTitle/__snapshots__/index.test.js.snap, src/components/PageTitle/index.js, src/components/PageTitle/index.test.js, styleguide/docs/components.md
Closes #49.
This doesn't _use_ `PageTitle` anywhere on our site yet but I'd like to integrate it into things after I get it merged and tweak the markdown output further in a separate PR. I think doing that after we have lists is best, because then I'll be able to use a lot of our base components for the style guide.
=> Feat: add page title

styleguide.config.js, styleguide/components/StyleGuide/index.js
Fixes #58.
Might as well take this for a spin locally, but it looks like:
again. 😄
=> fix: Use global emotion styles for styleguide

src/components/ui/List/Item.js, src/utils/CustomPropTypes.js
Tweak the error message to make it clear which component you _are_ using when getting this error message.
=> fix: Improve error message in custom prop type message

README.md
...because I keep forgetting the rules, so I'm sure other people might too.
Once we expand the "Contributing" section into a CONTRIBUTING.md, we should probably expand on what additional prefixes are cool, how to name branches, provide a bunch of examples, etc.
I assume we are following this: https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716
...but I am okay with being corrected!
=> docs: Add reference to commit conventions.

styleguide.config.js, styleguide/components/ComponentsList/index.js, styleguide/components/Playground/index.js, styleguide/components/SectionHeading/index.js, styleguide/components/StyleGuide/index.js, styleguide/components/TabButton/index.js, styleguide/components/slots/CodeTabButton.js, styleguide/components/slots/UsageTabButton.js
This is an attempt to make the styleguide a bit more usable & readable. It may or may not look super different.
I'd kinda love it if we could put an intro paragraph under the title, _then_ the "props" drop-down, but that may be harder. The props table itself still needs some work, but it would help to get your @tofumatt's opinion from a developer perspective about how we could make it more readable. (I have some thoughts, but I'd love to know how it's working for you since I expect you might  look at this more than me!)
A big improvement I think we could make here is making the sidebar navigation more self-contained—so maybe a slide-in (and out) element that would default to open on large screens, and closed for smaller ones. Something along these lines: …
=> Hierarchy refactoring of docs

styleguide.config.js
Close #114.
I used `en-CA` because it seems to be how we write English. Debate me! 😉
=> docs: Add an HTML lang attr

src/components/inline/Emphasis/index.js, src/components/inline/Emphasis/index.test.js, src/components/inline/Strong/index.js, src/components/inline/Strong/index.test.js, src/components/ui/Button/index.js, src/components/ui/Button/index.test.js, src/components/ui/Heading/index.js, src/components/ui/Heading/index.test.js, src/components/ui/Icon/index.js, src/components/ui/Icon/index.test.js, src/components/ui/Link/index.js, src/components/ui/Link/index.test.js, src/components/ui/List/Item.js, src/components/ui/List/Item.test.js, src/components/ui/List/index.js, src/components/ui/List/index.test.js, src/components/ui/PageTitle/index.js, src/components/ui/PageTitle/index.test.js, src/components/ui/Paragraph/index.js, src/components/ui/Paragraph/index.test.js, src/components/ui/Tabs/Tab.js, src/components/ui/Tabs/Tab.test.js, src/components/ui/Tabs/__snapshots__/Tab.test.js.snap, src/components/ui/Tabs/index.js, src/components/ui/Tabs/index.test.js, src/components/ui/TextField/index.js, src/components/ui/TextField/index.test.js
Fixes #117.
This is possibly a bit overkill but because we're a component library I'm assuming users will want the ability to reference the underlying DOM elements and am liberally forwarding `ref`s for now.
@sarahmonster You can probably rumber-stamp this if it passes the tests; feel free to look through and let me know if anything is confusing.
=> fix: Use forwardRef for all components

index.js, package.json
This removes the unneeded `index.js` and points webpack to our `src/` files.
=> chore: Update version and change main/module in package.json

styleguide/components/ComponentsList/index.js
If the styleguide is loaded without a hash (on master) the intro isn't selected in the menu. This changes that!
=> fix: Highlight intro link when no hash exists

src/components/ui/Button/README.md, src/components/ui/Button/index.js, src/components/ui/Button/index.test.js, src/components/ui/Link/index.js
Fixes #105 and uses our `Link` component instead of a plain `<a>` tag when `<Button navigation>` is used.
=> Fix: button navigation arrows

src/components/ui/Button/index.js
=> feat: Show a leading icon for Danger, Warning, and Success buttons.

src/components/ui/Link/index.js
Fixes #173 and also fixes https://github.com/octopusthink/octopusthink.com/issues/14.
If we wind up removing margins from components entirely (#163), this may be moot, but for now, it solves the problem and I can stop feeling a little batty every time I see it.
=> fix: Remove margin from external links.

src/components/ui/Button/__snapshots__/index.test.js.snap, src/components/ui/Button/index.js
The hover styles were driving me bananas—they looked clunky and didn't work well. This isn't perfect yet (and should be more themeable!) but it's a  big improvement, especially for the default and navigation buttons.
There's a wee issue where the → arrow doesn't appear for the default button until you hover over it:
.... probably just a CSS bug I'm too tired to catch.
=> fix: Fine-tune button hover styles.

src/components/ui/Button/__snapshots__/index.test.js.snap, src/components/ui/Button/index.js
Fix #181
It's worth testing and tweaking this. The other option here would be to unset the transition entirely (`0ms`) or use `50ms`. Let me know which you prefer, but I think this makes the movement of the button when clicking on it feel much more "immediate", which is a nicer UX.
=> fix: Button :active state transition delay

src/components/ui/Paragraph/index.js, src/components/ui/Tags/index.js
Before:
After:
Fixes #162.
Also replaces a custom Paragraph used for list title with our VisuallyHidden component, since it's now available for use.
=> fix: Improve Tag wrapping.

src/components/ui/Link/__snapshots__/index.test.js.snap, src/components/ui/Link/index.js, src/components/ui/SkipLink/__snapshots__/index.test.js.snap
This is more consistent with focus states used elsewhere (ie, for buttons) and avoids weirdness where sometimes the background is too dark, and the contrast gets shot, like this:
Before:
Ultimately, we'll want to rejig the Link (and Button) components to allow for super-flexible hover and focus styling, but for now, this should give us a more consistent and sensible default behaviour. See also #200, which I've just filed.
And it should help with https://github.com/octopusthink/getmicdrop.com/issues/11, which is basically why I'm bothering to fix this now. 😜
=> feat: Change link focus style to an outline.

package-lock.json, package.json
Should fix issues encountered in https://github.com/octopusthink/getmicdrop.com/pull/20.
Fixes #191.
Unfortunately this invalidates #189 (which was the fix for #188). This means any project using Nautilus requires emotion as a dependency, but frankly that's not the end-of-the-world. If you aren't using Emotion, it might be awkward to use Nautilus. C'est la vie.
=> fix: Use emotion as a peer dependency

.github/workflows/tests.yml, src/components/ui/Icon/index.js, src/components/ui/TextField/README.md, src/components/ui/TextField/__snapshots__/index.test.js.snap, src/components/ui/TextField/index.js, src/components/ui/TextField/index.test.js
This introduces icons in TextFields, which will close #84 and also set groundwork for the ComboBox component being slowly built in #206. 
It introduces the concept of a "signifier icon" (one that communicates meaning) and an "action icon" (one you can click on to do stuff), with consistent placement inside the input. They're currently styled in the same way but that will change later, once the action icon actually has the ability to do something.
What I need help with:
- Making action icons actually be able do something. They should probably use a Button component with an Icon inside—I'm working on this in a separate PR but it's not quite ready yet. If we can easily pass an action callback to the icon and have that work in a sensible way here, that might be easier, and we can improve …
=> feat: Allow for icons in TextField

src/components/ui/Link/__snapshots__/index.test.js.snap, src/components/ui/Link/index.js, src/components/ui/SkipLink/__snapshots__/index.test.js.snap
This fixes a couple of little things, namely links in paragraphs messing with line-heights (#218) and generally looking a bit awkward, and the external link indication being way too agressive (#217). It switches from using a border-bottom for the link to an _actual text decoration_, (who knew!) because it's a bit smarter that way.
**Before:**
**After:**
=> fix: Improve Link behaviour

src/components/ui/Link/__snapshots__/index.test.js.snap, src/components/ui/Link/index.js, src/components/ui/SkipLink/__snapshots__/index.test.js.snap
Apparently there's no support for text-decoration fanciness in Chrome or Edge, so let's revert back to using box-shadow, at least until support improves.
Before:
After:
=> fix: Fix link underlines in Blink browsers.

src/components/ui/Tabs/Tab.js, src/components/ui/Tabs/Tab.test.js, src/components/ui/Tabs/__snapshots__/Tab.test.js.snap, src/components/ui/Tabs/__snapshots__/index.test.js.snap
Visually, these don't make sense to show since the tab itself already provides this context. My suspicion is that we'd always intended to hide these, but perhaps didn't originally for lack of a VisuallyHidden component? Maybe?
Before:
After:
We're also switching it from a heading to a tab to ensure consistent heading hierarchy. If we wanted to stick with headings, I might recommend opting for something higher, like an h2, which is more likely to work with the page hierarchy, or pass a prop to declare the heading level. I could see the value in showing these as headings, so I'm not sure about the Paragraph approach here—maybe instead we should make them h1s or h2s by default, but allow users to pass through a different heading level if needed?
=> fix: Hide tab headings.
