octopusthink/nautilus

src/base/typography/typographyVariables.js
src/components.js
src/components/input/Card/Button.spec.js
src/components/input/Card/Card.js
src/components/input/Card/Card.md
src/components/input/Card/Card.styles.js
src/components/input/Card/__snapshots__/Button.spec.js.snap
src/components/input/Card/index.js
src/components/typography/Heading/Heading.md

I'm aiming for something along these lines:
Where it's currently at:

Add card component

---

docs/typographyVariables.md
src/base/color/colorVariables.js
src/base/typography/fonts.js
src/base/typography/typographyVariables.js
src/components/input/Button/Button.js
src/components/input/Button/Button.md
src/components/input/Button/Button.styles.js
src/components/input/Card/Card.js
src/components/input/Card/Card.md
src/components/typography/Heading/Heading.js
src/components/typography/Heading/Heading.md
src/components/typography/Heading/Heading.styles.js
src/components/typography/Paragraph/Paragraph.js
src/components/typography/Paragraph/Paragraph.md
src/components/typography/Paragraph/Paragraph.styles.js
src/global.css
src/index.js
styleguide-ui/VariableTable.js

Trying to make base and brand variables make sense. It's something of an uphill battle.
Still to do:

Update typography variables

---

azure-pipelines.yml
bin/publish-gh-pages.js
package-lock.json
package.json

Should publish all branches to our `gh-pages` branch, including PRs!

feat: publish to gh-pages

---

azure-pipelines.yml
bin/publish-gh-pages.js

Tweak the git branch variables.

fix: Improve pipeline

---

src/styleguide/docs/components.md
src/styleguide/load-components.js

Just a little tweak that displays all the components on the page.

feat: Add a list of components to components page

---

.gitignore
src/components/Button/README.md
src/components/Paragraph/README.md

Adjusts the Markdown to look nicer in editors (especially Atom!)

fix: Tweak JSX Markdown and .gitignore

---

src/styleguide/docs/principles.md
styleguide.config.js

Closes #23.
They will look prettier once we can style things (see #25!) but for now they're just text.
@tofumatt want to give me a quick review? This is basically just the same text as Notion, so probably just needs a thumbs-up.

Add a first draft of our design principles.

---

bin/publish-gh-pages.js

fix: Publish the right dir to gh-pages

---

styleguide.config.js
styleguide/components/Code/index.js
styleguide/components/Playground/index.js
styleguide/components/TabButton/index.js

Improve styleguide styles

---

src/components/ui/List/index.js
src/components/ui/List/index.test.js

This is just an optimisation/code PR that doesn't affect implementation (notice the tests haven't changed, just been expanded).
No review really needed.

fix: Improve list component ID generation

---

README.md
src/components/ui/Heading/__snapshots__/index.test.js.snap
src/components/ui/List/__snapshots__/index.test.js.snap
src/components/ui/PageTitle/__snapshots__/index.test.js.snap
src/components/ui/Paragraph/__snapshots__/index.test.js.snap
src/themes/nautilus/index.js
styleguide.config.js
styleguide/components/ComponentsList/index.js
styleguide/components/Footer/index.js
styleguide/components/Header/index.js
styleguide/components/StyleGuide/index.js
styleguide/components/TableOfContents/index.js

This got a bit away from me a wee bit, but it's basically a bunch of meta improvements to the README as well as to the actual Nautilus site itself.

Improve project overview description & general site

---

README.md

Very minor copyediting changes live here.

chore: Add 🦄 ❤️ 🍆 to README, and credit Feather icons.

---

package-lock.json
package.json
src/components/index.js

New components in this release are:
* `<Emphasis>`
* `<Icon>`
* `<Link>`
* `<Strong>`
* `<Tab>`
* `<TextInput>`
**Fun fact:** Archaea have no cell nucleus!

chore: Update version for release (0.2.0)

---

package-lock.json
package.json
src/components/hoc/Nautilus/index.js
styleguide/components/ComponentsList/index.js
styleguide/components/Footer/index.js
styleguide/components/Header/index.js
styleguide/components/Markdown/Markdown.js
styleguide/components/StyleGuide/index.js
styleguide/components/TableOfContents/index.js

Still in-progress, but already waaaaaaaay better:

Implement a better sidebar paradigm

---

styleguide/components/ComponentsList/index.js
styleguide/components/StyleGuide/index.js

Fix #106.
@sarahmonster: You'll likely want to tweak the actual styles in use here; mine are obviously terrible and just a proof-of-concept.

fix: Add current page awareness to navigation

---

package-lock.json
package.json
src/components/inline/Emphasis/index.test.js
src/components/inline/Strong/index.test.js
src/components/ui/Button/index.test.js
src/components/ui/Heading/index.test.js
src/components/ui/Icon/index.test.js
src/components/ui/Link/index.test.js
src/components/ui/List/index.test.js
src/components/ui/PageTitle/index.test.js
src/components/ui/Paragraph/index.test.js
src/components/ui/Tabs/index.test.js
src/components/ui/TextField/__snapshots__/index.test.js.snap
src/components/ui/TextField/index.js
src/components/ui/TextField/index.test.js
utils/jest.setup.js
utils/testing.js

Adds automated accessibility tests and improves the accessibility requirements of our TextField component.

feat: Add aXe testing and improve label prop in TextField

---

src/components/ui/Link/index.js
src/components/ui/SkipLink/README.md
src/components/ui/SkipLink/__snapshots__/index.test.js.snap
src/components/ui/SkipLink/index.js
src/components/ui/SkipLink/index.test.js
styleguide/components/Playground/index.js

Fix #74.
Fixes an issue with the Link component's ref handling, as well.

feat: Add SkipLink component

---

README.md

I find these helpful when evaluating libraries; any opposition to adding them here?

docs: Add badges to README header

---

src/components/ui/Button/index.js
src/components/ui/Icon/README.md
src/components/ui/Icon/index.js
src/components/ui/List/Item.js
src/components/ui/TextField/index.js
src/themes/nautilus/index.js
src/themes/propTypes.js
src/themes/styleguide/index.js
styleguide/components/Code/index.js
styleguide/components/Footer/index.js
styleguide/components/Playground/index.js
styleguide/components/StyleGuide/index.js
styleguide/components/TabButton/index.js

No more extraSmall xxs weirdness! ✨
I am 89% sure I got them all, but would love a confidence check here.
Closes #104.

feat: Use established size variables for margin and spacing values.

---

package-lock.json
package.json
src/components/hoc/Nautilus/README.md
src/components/hoc/Nautilus/index.js
src/components/hoc/Nautilus/index.test.js
src/components/ui/Button/README.md
src/components/ui/Button/index.js
src/components/ui/Button/index.test.js
src/components/ui/Link/README.md
src/components/ui/Link/__snapshots__/index.test.js.snap
src/components/ui/Link/index.js
src/components/ui/Link/index.test.js
src/components/ui/SkipLink/index.js
src/components/ui/SkipLink/index.test.js
src/components/ui/Tabs/README.md
styleguide/components/Wrapper/index.js
utils/testing.js

feat: Use <a> tag by default in Link component

---

package-lock.json
src/components/index.js
src/index.js
src/index.test.js
src/styles/index.js

This adds style helper exports, but also adds tests to make sure they work better. It also includes `<SkipLink>` for real! 😆

feat: Add styles exports and styling tests

---

src/components/index.js
src/components/ui/SkipLink/__snapshots__/index.test.js.snap
src/components/ui/SkipLink/index.js
src/components/ui/VisuallyHidden/README.md
src/components/ui/VisuallyHidden/__snapshots__/index.test.js.snap
src/components/ui/VisuallyHidden/index.js
src/components/ui/VisuallyHidden/index.test.js

feat: Add VisuallyHidden component

---

styleguide/components/StyleGuide/index.js
webpack.config.js

Adds privacy-based analytics to the site, in production-only.

feat: Add analytics to site

---

src/components/ui/Heading/index.test.js
src/components/ui/List/index.js
src/components/ui/List/index.test.js

Fix: list children output

---

package-lock.json
package.json

fix: Require Emotion as a dependency

---

.github/workflows/publish-package.yml
.github/workflows/publish-styleguide.yml
.github/workflows/tests.yml

This optimises our GitHub actions with caching and uses `npm ci` over `npm install`.

chore: Optimise all GitHub actions with caching

---

src/components/ui/SkipLink/__snapshots__/index.test.js.snap
src/components/ui/SkipLink/index.js

fix: SkipLink unstyled should unstyle underlying Link

---

src/components/ui/Button/README.md
src/components/ui/Button/__snapshots__/index.test.js.snap
src/components/ui/Button/index.js
src/components/ui/Button/index.test.js
src/components/ui/Link/index.js
src/components/ui/Link/index.test.js

fix: Button and Links!

---

src/components/ui/SkipLink/__snapshots__/index.test.js.snap
src/components/ui/SkipLink/index.js
src/components/ui/VisuallyHidden/__snapshots__/index.test.js.snap
src/components/ui/VisuallyHidden/styles.js

Fix: 222 VisuallyHidden Styles

---

src/components/ui/ComboBox/Heading.js
src/components/ui/ComboBox/Option.js
src/components/ui/ComboBox/index.js
src/components/ui/TextField/index.js

This covers a few wee little fixes, namely:
- adds the noMargin prop (yay!)
- tightens spacing of individual items so it's easier to scan the list
- vertically aligns icons in text fields more consistently
It's basically just some super basic CSS fixes, so should be a nice quick easy review.

fix: ComboBox incompatibilities

---

.eslintrc.js
package-lock.json
package.json
src/components/index.js
src/components/ui/ComboBox/README.md
src/components/ui/ComboBox/index.js
src/components/ui/Icon/index.test.js
src/components/ui/Select/IndicatorsContainer.js
src/components/ui/Select/Menu.js
src/components/ui/Select/MultiValue.js
src/components/ui/Select/Option.js
src/components/ui/Select/Placeholder.js
src/components/ui/Select/README.md
src/components/ui/Select/SelectContainer.js
src/components/ui/Select/index.js
src/components/ui/Tags/index.js
src/components/ui/Tags/index.test.js
src/components/ui/TextField/index.js
src/components/ui/TextField/index.test.js

feat: Add a Select component.
